# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainDlg.ui'
#
# Created: Mon Apr 30 18:28:24 2018
#      by: pyside2-uic  running on PySide2 5.9.0a1.dev1524639684
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(501, 266)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 479, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LayoutTargetFolder = QtWidgets.QHBoxLayout()
        self.LayoutTargetFolder.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.LayoutTargetFolder.setObjectName("LayoutTargetFolder")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.LayoutTargetFolder.addWidget(self.label)
        self.EditTargetFolder = QtWidgets.QLineEdit(self.layoutWidget)
        self.EditTargetFolder.setObjectName("EditTargetFolder")
        self.LayoutTargetFolder.addWidget(self.EditTargetFolder)
        self.BtnBrowse = QtWidgets.QPushButton(self.layoutWidget)
        self.BtnBrowse.setObjectName("BtnBrowse")
        self.LayoutTargetFolder.addWidget(self.BtnBrowse)
        self.verticalLayout.addLayout(self.LayoutTargetFolder)
        self.LayoutOutput = QtWidgets.QHBoxLayout()
        self.LayoutOutput.setObjectName("LayoutOutput")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.LayoutOutput.addWidget(self.label_3)
        self.EditOutput = QtWidgets.QLineEdit(self.layoutWidget)
        self.EditOutput.setText("")
        self.EditOutput.setObjectName("EditOutput")
        self.LayoutOutput.addWidget(self.EditOutput)
        self.BtnOutputBrowse = QtWidgets.QPushButton(self.layoutWidget)
        self.BtnOutputBrowse.setObjectName("BtnOutputBrowse")
        self.LayoutOutput.addWidget(self.BtnOutputBrowse)
        self.verticalLayout.addLayout(self.LayoutOutput)
        self.LayoutHashMethod = QtWidgets.QHBoxLayout()
        self.LayoutHashMethod.setObjectName("LayoutHashMethod")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.LayoutHashMethod.addWidget(self.label_6)
        self.RadBtnCrc32 = QtWidgets.QRadioButton(self.layoutWidget)
        self.RadBtnCrc32.setChecked(True)
        self.RadBtnCrc32.setObjectName("RadBtnCrc32")
        self.LayoutHashMethod.addWidget(self.RadBtnCrc32)
        self.RadBtnMD5 = QtWidgets.QRadioButton(self.layoutWidget)
        self.RadBtnMD5.setObjectName("RadBtnMD5")
        self.LayoutHashMethod.addWidget(self.RadBtnMD5)
        self.RadBtnSHA1 = QtWidgets.QRadioButton(self.layoutWidget)
        self.RadBtnSHA1.setObjectName("RadBtnSHA1")
        self.LayoutHashMethod.addWidget(self.RadBtnSHA1)
        self.verticalLayout.addLayout(self.LayoutHashMethod)
        self.LayoutIgnorePat = QtWidgets.QHBoxLayout()
        self.LayoutIgnorePat.setObjectName("LayoutIgnorePat")
        self.ChkBoxIgnore = QtWidgets.QCheckBox(self.layoutWidget)
        self.ChkBoxIgnore.setEnabled(True)
        self.ChkBoxIgnore.setObjectName("ChkBoxIgnore")
        self.LayoutIgnorePat.addWidget(self.ChkBoxIgnore)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.LayoutIgnorePat.addWidget(self.label_5)
        self.EditIgnorePattern = QtWidgets.QLineEdit(self.layoutWidget)
        self.EditIgnorePattern.setEnabled(False)
        self.EditIgnorePattern.setObjectName("EditIgnorePattern")
        self.LayoutIgnorePat.addWidget(self.EditIgnorePattern)
        self.verticalLayout.addLayout(self.LayoutIgnorePat)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.EditSourceExtList = QtWidgets.QLineEdit(self.layoutWidget)
        self.EditSourceExtList.setObjectName("EditSourceExtList")
        self.horizontalLayout.addWidget(self.EditSourceExtList)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.LayoutExtOnly = QtWidgets.QHBoxLayout()
        self.LayoutExtOnly.setObjectName("LayoutExtOnly")
        self.ChkBoxExtOnly = QtWidgets.QCheckBox(self.layoutWidget)
        self.ChkBoxExtOnly.setObjectName("ChkBoxExtOnly")
        self.LayoutExtOnly.addWidget(self.ChkBoxExtOnly)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.LayoutExtOnly.addWidget(self.label_2)
        self.EditExtList = QtWidgets.QLineEdit(self.layoutWidget)
        self.EditExtList.setEnabled(False)
        self.EditExtList.setObjectName("EditExtList")
        self.LayoutExtOnly.addWidget(self.EditExtList)
        self.verticalLayout.addLayout(self.LayoutExtOnly)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ChkBoxClocUse = QtWidgets.QCheckBox(self.layoutWidget)
        self.ChkBoxClocUse.setObjectName("ChkBoxClocUse")
        self.horizontalLayout_2.addWidget(self.ChkBoxClocUse)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.EditClocPath = QtWidgets.QLineEdit(self.layoutWidget)
        self.EditClocPath.setEnabled(False)
        self.EditClocPath.setObjectName("EditClocPath")
        self.horizontalLayout_2.addWidget(self.EditClocPath)
        self.BtnClocPathBrowse = QtWidgets.QPushButton(self.layoutWidget)
        self.BtnClocPathBrowse.setEnabled(False)
        self.BtnClocPathBrowse.setObjectName("BtnClocPathBrowse")
        self.horizontalLayout_2.addWidget(self.BtnClocPathBrowse)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.LayoutStartExitButton = QtWidgets.QHBoxLayout()
        self.LayoutStartExitButton.setObjectName("LayoutStartExitButton")
        self.BtnStart = QtWidgets.QPushButton(self.layoutWidget)
        self.BtnStart.setObjectName("BtnStart")
        self.LayoutStartExitButton.addWidget(self.BtnStart)
        self.BtnExit = QtWidgets.QPushButton(self.layoutWidget)
        self.BtnExit.setObjectName("BtnExit")
        self.LayoutStartExitButton.addWidget(self.BtnExit)
        self.verticalLayout.addLayout(self.LayoutStartExitButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "FilesInfoReader GUI", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "TargetFolder", None, -1))
        self.BtnBrowse.setText(QtWidgets.QApplication.translate("Dialog", "Browse", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Output", None, -1))
        self.BtnOutputBrowse.setText(QtWidgets.QApplication.translate("Dialog", "Browse", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Hash", None, -1))
        self.RadBtnCrc32.setText(QtWidgets.QApplication.translate("Dialog", "CRC32", None, -1))
        self.RadBtnMD5.setText(QtWidgets.QApplication.translate("Dialog", "MD5", None, -1))
        self.RadBtnSHA1.setText(QtWidgets.QApplication.translate("Dialog", "SHA1", None, -1))
        self.ChkBoxIgnore.setText(QtWidgets.QApplication.translate("Dialog", "Ignore", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Pattern", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Source Ext", None, -1))
        self.ChkBoxExtOnly.setText(QtWidgets.QApplication.translate("Dialog", "Ext Only", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Extensions", None, -1))
        self.ChkBoxClocUse.setText(QtWidgets.QApplication.translate("Dialog", "CLOC use", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "Cloc Path", None, -1))
        self.BtnClocPathBrowse.setText(QtWidgets.QApplication.translate("Dialog", "Browse", None, -1))
        self.BtnStart.setText(QtWidgets.QApplication.translate("Dialog", "Start", None, -1))
        self.BtnExit.setText(QtWidgets.QApplication.translate("Dialog", "Exit", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

